export const foodItems = [
  {
    id: "1",
    title: "돈까스",
    img: "https://next-js-worldcup-foods.s3.ap-northeast-2.amazonaws.com/katsu.jpg",
    info: "맛있는 돈까스",
    url: "",
  },
  {
    id: "2",
    title: "비빔밥",
    img: "https://next-js-worldcup-foods.s3.ap-northeast-2.amazonaws.com/bibimbab.jpg",
    info: "",
    url: "",
  },
  {
    id: "3",
    title: "스시",
    img: "https://next-js-worldcup-foods.s3.ap-northeast-2.amazonaws.com/sushi.jpg",
    info: "",
    url: "",
  },
  {
    id: "4",
    title: "스테이크",
    img: "https://next-js-worldcup-foods.s3.ap-northeast-2.amazonaws.com/stake.jpg",
    info: "",
    url: "",
  },
  {
    id: "5",
    title: "김치찌개",
    img: "https://next-js-worldcup-foods.s3.ap-northeast-2.amazonaws.com/kimchisoup.png",
    info: "",
    url: "",
  },
  {
    id: "6",
    title: "피자",
    img: "https://next-js-worldcup-foods.s3.ap-northeast-2.amazonaws.com/pizza.jpg",
    info: "",
    url: "",
  },
  {
    id: "7",
    title: "라면",
    img: "https://next-js-worldcup-foods.s3.ap-northeast-2.amazonaws.com/ramen.jpg",
    info: "",
    url: "",
  },
  {
    id: "8",
    title: "카레",
    img: "https://next-js-worldcup-foods.s3.ap-northeast-2.amazonaws.com/curry.jpg",
    info: "",
    url: "",
  },
];
