import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import NavBar from "../components/NavBar";

export default function Home() {
  return (
    <>
      <NavBar />
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Hello World!
          </h1>

          <p className={styles.description}>
            Next.js 로 이것저것 만들기 😎
          </p>

          <div className={styles.grid}>
            <Link href="/games/worldcup">
              <a className={styles.card}>
                <h2>음식 월드컵 &rarr;</h2>
                <p>내가 가장 좋아하는 음식은?</p>
              </a>
            </Link>

          </div>
        </main>

        <footer className={styles.footer}>
          <p>
            Created by <span>Dal-ya</span>
          </p>
        </footer>
      </div>
    </>
  );
}
